use company
show collections
db.createCollection("employee")
db.employee.insertMany(
  [                     {_id : 1,
                         name : "Peter",
                         job : "clerk",
                         salary : {basic : 900,
                                   dapct : 70,
                                   travel : 250,
                                   health : 300},
                         dept : "research"},
                        {_id : 2,
                         name : "Turner",
                         job : "salesman",
                         salary : {basic : 1000,
                                   dapct : 60,
                                   travel : 500,
                                   health : 400,
                                   comm : 200},
                         dept : "sales"},
                        {_id : 3,
                         name : "Allen",
                         job : "manager",
                         salary : {basic : 3000,
                                   dapct : 90,
                                   travel : 850,
                                   health : 500,
                                   house : 900},
                         dept : "sales"},
                        {_id : 4,
                         name : "Miller",
                         job : "analyst",
                         salary : {basic : 2500,
                                   dapct : 85,
                                   health : 400,
                                   overtime : 500,
                                   house : 800},
                         medical : 700,
                         dept : "research"},
                        {_id : 5,
                         name : "King",
                         job : "manager",
                        salary : {basic : 3000,
                                   dapct : 90,
                                   travel : 850,
                                   health : 500,
                                   house : 900},
                         dept : "research"},
                        {_id : 6,
                         name : "Smith",
                         job : "clerk",
                         salary : {basic : 900,
                                   dapct : 70,
                                   travel : 200,
                                   health : 400},
                         dept : "accounts"},
                        {_id : 7,
                         name : "Ford",
                         job : "manager",
                         salary : {basic : 3000,
                                   dapct : 90,
                                   travel : 750,
                                   health : 400,
                                   house : 800},
                         dept : "accounts"},
                        {_id : 8,
                         name : "Jones",
                         job : "clerk",
                         salary : {basic : 800,
                                   dapct : 70,
                                   travel : 150,
                                   health : 300},
                         dept : "accounts"}]
)
//using the elemMatch in the case of nested document only without any array as
db.employee.find({})
db.employee.find({salary:{basic:1000,dapct:60,travel:500,health:400,comm:200}})
//fetching the dictinct element in this case 
db.employee.distinct("salary.basic");